/*
 * File:   gpio.c
 * Author: Abdelaziz Sayed
 *
 * Created on July 20, 2020, 10:05 PM
 */
#include"gpio.h"

void GPIO_Init(void)
{
    SET_PIN_DIRECTION(_UpButton_DIRECTION_,_UpButton_PIN_,INPUT);
    SET_PIN_DIRECTION(_DownButton_DIRECTION_,_DownButton_PIN_,INPUT);
    SET_PIN_DIRECTION(_DIGIT1_DIRECTION_,_DIGIT1_PIN_,OUTPUT);
    SET_PIN_DIRECTION(_DIGIT2_DIRECTION_,_DIGIT2_PIN_,OUTPUT);
    SET_PIN_DIRECTION(_DIGIT3_DIRECTION_,_DIGIT3_PIN_,OUTPUT);
    SET_PIN_DIRECTION(_DIGIT4_DIRECTION_,_DIGIT4_PIN_,OUTPUT);
    SET_PORT_DIRECTION(_SSD_PORT_DIRECTION_,OUTPUT);
    SET_PIN_DIRECTION(_LED4_DIRECTION_,_LED4_PIN_,OUTPUT);
    SET_PIN_DIRECTION(_LED3_DIRECTION_,_LED3_PIN_,OUTPUT);
}